#!/usr/bin/php
<?php

$required = [
    'Const.php',
    'Vendor/autoload.php',
];

require 'dependencies.php';

loadDependencies($required);

$request = new \App\Library\Io\Request($argv, $argc);
$main    = new \App\Main($request);
$main->run();
// That's all folks !
//echo json_encode($output), "\n";
